# Generated by Django 2.1.7 on 2019-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='contactNumber',
            field=models.IntegerField(),
        ),
    ]
