# Generated by Django 2.1.7 on 2019-03-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='contactNumber',
            new_name='contactNo',
        ),
        migrations.AddField(
            model_name='userdata',
            name='securityQueAns',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='securityQuestion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
