# Generated by Django 2.1.7 on 2019-03-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0002_auto_20190327_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='securityQueAns',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='securityQuestion',
            new_name='security_question',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='contactNo',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='userName',
        ),
        migrations.AddField(
            model_name='userdata',
            name='contactno',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='userdata',
            name='lastname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='security_answer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
