# Generated by Django 2.1.7 on 2019-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0002_auto_20190327_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='DOB',
            field=models.DateField(),
        ),
    ]
