# Generated by Django 2.1.7 on 2019-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0003_auto_20190327_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='contactNumber',
            field=models.CharField(max_length=10),
        ),
    ]
