# Generated by Django 2.1.7 on 2019-03-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0004_auto_20190327_1238'),
        ('userData', '0003_auto_20190328_0659'),
    ]

    operations = [
    ]
