# Generated by Django 2.1.7 on 2019-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
