# Generated by Django 2.2 on 2019-04-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='sequrity_qns',
            new_name='sequrity_ans',
        ),
    ]
